name: Build Golang Docker Image

于:
  push:
    分支: [ golang ]
    paths:
      - 'Dockerfile'
      - 'index.html'
      - 'main.go'
  pull_request:
    分支: [ golang ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: golang 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: 。
          push: true
          platforms: linux/amd64,linux/arm64
          标签: |
            ghcr.io/${{ github.repository_owner }}/galaxyaohui:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=websocket server
            org.opencontainers.image.licenses=GPL
          cache-from: type=gha
          cache-to: type=gha,mode=max
